FROM apache/airflow:2.10.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY --chown=airflow:airflow . /opt/airflow/project

RUN pip install --no-cache-dir -r /opt/airflow/project/requirements.airflow.txt
